### ISSUE TITLE
Tabs vs. spaces

### ISSUE THREAD

**Issue by ghost** [kevoreilly/capemon#8] opened 2021-03-01 18:19 UTC
Hi, we are moving from our old cuckoo-modified fork to CAPEv2 and I noticed that tabs and spaces are used randomly across the code base. Would you consider fixing this? This would greatly help us with merging our changes (some of which we plan to contribute after the migration) and generally with development later. Should be easy to do with the help of the Visual Studio or some other IDE.

I am willing to do this and create PR. However, I think it would be easier for you to do this on your own then going over the diff in the PR from a stranger. If you want to this and you do not mind a PR, let me know if you would prefer tabs or spaces (we prefer tabs).

**Comment by kevoreilly** [comment] 2021-03-11 06:26
Hi mbandzi - yes absolutely I will fix this. I had fixed a few that I noticed myself randomly - I think my use of Notepad++ for both Python and C is probably the root cause here! But obviously no good reason for it and happy to fix that up if it will help you. Thanks for bringing it to my attention! Many improvements to be had in capemon over cuckoomon-modified for sure...

**Comment by kevoreilly** [comment] 2021-03-16 15:45
This is now fixed in https://github.com/kevoreilly/capemon/commit/68c44447d41903f14177a82d51b6d47bb12ca482 - indentation spaces changed to tabs.

Please let me know if there are any issues or I can do anything else to help. Thank you

**Closed as completed by kevoreilly** 2021-03-16 15:45 UTC

**Comment by ghost** [comment] 2021-03-16 19:56
Hi, thanks!

Just to be sure you know this, the formatting broke alignment of some definitions. It may be best to do this only for spaces that are at the start of the line and keep the spaces inside.

**Comment by kevoreilly** [comment] 2021-03-25 11:14
That was unfortunate - I'll try and correct this going forward. Let me know if there is anything else - I am optimistic at the prospect of seeing some merges.
