### ISSUE TITLE
CoCreateInstance hook Win64 exclusion

### ISSUE THREAD

**Issue by meck-gd** [kevoreilly/capemon#60] opened 2023-04-20 12:16 UTC
I'm currently fixing up some code in the CoCreateInstance(Ex) hooks where a GUID for Task Scheduler 1.0 objects was missing.

In https://github.com/kevoreilly/capemon/commit/01cc21dcb153643f47674dbb8d218771fa59d603 x64 was excluded from sending pipe commands, apparently due to some issue with maldocs, but I couldn't find any more information about what exactly the problem was.

As it stands, for 64-bit malware that persists itself using a scheduled task and only then becomes active, CAPE doesn't currently track execution of the scheduled task malware process. Do you think anything speaks against at least enabling the `TASKSCHED` command for all platforms and excluding only `WMI`, `BITS` and `INTEROP`? 

If there are no concerns, I'll create a PR with the changes.

**Comment by cccs-mog** [comment] 2023-04-25 17:51
I would be interested in having the tracking enabled for at least TASKSCHED and BITS also. Wondering what the issue was in the first place. Currently working into that but a sample/hint into where the problem was originating would help. Could do the PR and/or work with someone to find/fix the root cause.

Thanks.

**Comment by kevoreilly** [comment] 2023-04-25 19:22
Hi - apologies for the late reply. The hook exclusion needs revisiting, I will see if I can find the maldoc tests that failed and look into them further with a view to re-enabling at least some of these messages for x64. Thanks for pointing this out, I will try and look at this tomorrow.

**Comment by kevoreilly** [comment] 2023-08-22 16:02
This is now fixed.

**Closed as completed by kevoreilly** 2023-08-22 16:02 UTC
